# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Example Linter & CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
        types: [opened, synchronize]
    pull_request_target:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
            issues: 'write'
            actions: read
            security-events: write

        steps:
            - uses: actions/checkout@v3
            # - uses: ArtiomTr/jest-coverage-report-action@v2
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       base_path: 'src/'
            #       threshold: 80
            - name: Setup node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
            - run: npm install --save
            - run: npm run lint
            - run: npm run test
