name: 'coverage'
on:
    pull_request_target:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
            issues: 'write'
            actions: read
            security-events: write
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
